### ISSUE TITLE
Fehlendes Icon auf FAQ Seite

### ISSUE THREAD

**Issue by GeoDodo** [fossgis/openstreetmap.de#14]
Auf der Seite https://www.openstreetmap.de/faq.html wird aktuell bei "Fehler melden"auf ein Icon von Openstreetmap.org verlinkt. Dies scheint aber so nicht mehr zu existieren. Daher sind man nur ein schwarzes Kästchen.

**Comment by ValorNaram** [comment]
Wurde dieser Bug nicht schon behoben?

**Comment by joto** [comment]
Ja, das tut.
