### ISSUE TITLE
automatische Updates der Webseite

### ISSUE THREAD

**Issue by gislars** [fossgis/openstreetmap.de#2]
Um die Aktualisierung der Webseite für jedermann zu ermöglichen schlage ich folgenden Workflow vor:
- Änderungen werden per Pull-Request angenommen
- Cronjob um Änderungen vom Repository zu holen

Offene Punkte:
- [x] Updatescript auf dem Server erstellen
- [ ] Updatescript testen und aktivieren

Eine Lösung für Liveupdates per Webhooks/Notifications wäre eleganter aber auch komplexer und aufwändiger zu erstellen/warten.

**Comment by giggls** [comment]
Gibt es laut Aussage von Max. Techter seit 16 Feb 2017.

 Funktioniert auch. Mein Pull-request von gestern ist bereits live :)

IMO kann man diesen issue also schließen.
