### ISSUE TITLE
FAQ ergänzen - Löschen von OSM.org Konto

### ISSUE THREAD

**Issue by GeoDodo** [fossgis/openstreetmap.de#20]
Wir bekommen regelmässig Anfragen wie man sein OSM-Konto wieder löscht. Auch wenn die Webseite damit selber nichts zu tun hat, sollten wir diesen Punkt in die FAQs mit aufnehmen.

**Comment by ValorNaram** [comment]
Wie löscht man den sein OSM-Konto?
