### ISSUE TITLE
Maßstab hinzufügen

### ISSUE THREAD

**Issue by woodpeck** [fossgis/openstreetmap.de#31]
An webmaster@fossgis gehen regelmäßig Mails, in denen sich Nutzer einen Maßstab wünschen. Beispiel von gerade eben:

> die deutsche web-Seite würde sehr gewinnen, wenn Ihr (1) einen Maßstab
> mit in die Karte einblenden würdet und auch (2) ein Lineal zur
> Abstandsmessung zur Verfügung stellen würdet.

Ich antworte dann oft sowas wie:

> Das ist schwierig. Die bei OSM benutzte sphärische Mercator-Projektion
> kann, je nachdem, welchen Kartenausschnitt man anzeigt, unterschiedliche
> Maßstäbe in Längs- und Querrichtung haben, und zudem ist der Maßstab am
> oberen und unteren Bildschirmrand nicht der gleiche. Ein
> kartographischer Maßstab wäre also allenfalls eine "Näherungslösung",
> die nach unserer Ansicht zu mehr Verwirrung führt, als er nützt.
> 
> Auf www.openstreetmap.org sehen Sie einen Maßstab in der unteren linken
> Ecke - dort hat man sich also anders entschieden. (Merken Sie, wie sich
> der Maßstab verändert, wenn Sie die Karte nach oben und unten schieben?)

Ändert aber nichts dran, dass die Leute trotzdem einen Maßstab wollen ;)

**Comment by giggls** [comment]
Der eigentliche "issue" ist da ja IMO, dass man das mal mit Leaflet oder einem Openlayers >=3 neu machen sollte. AFAIK ist das immer noch ein OL2.

**Comment by joto** [comment]
Ich  habe jetzt mal die eine Zeile eingefügt, die dafür sorgt, dass ein Maßstab angezeigt wird. Alles andere muss mal jemand anderes machen.
