### ISSUE TITLE
Link "Datenschutz" zeigt auf nicht existente Seite

### ISSUE THREAD

**Issue by giggls** [fossgis/openstreetmap.de#33]
Sollte das nicht nach https://fossgis.de/datenschutzerkl%C3%A4rung/ zeigen?

**Comment by Nakaner** [comment]
Ist schon in https://github.com/fossgis/fossgis-webseite behoben worden.

**Comment by lyxys** [comment]
Funktioniert aber nicht, da der Link jetzt auf "datenschutzerklaerung" mit "ae" zeigt, die eigentliche Zielseite sich aber mit "ä" schreibt.

**Comment by lyxys** [comment]
Das scheint ein echt schwieriges Problem zu sein. Es funktioniert jedenfalls immer noch nicht.

**Comment by joto** [comment]
Als der Link von https://www.openstreetmap.de/ tut jetzt bei mir. @lyxys Was genau tut bei Dir nicht. Bitte vorher mal ein Shift-Reload machen.

**Comment by lyxys** [comment]
Heute funktioniert es bei mir auch. Gestern war da noch der Link mit "ae", trotz ctrl-F5.
