### ISSUE TITLE
Yapis does not exist anymore

### ISSUE THREAD

**Issue by Strubbl** [fossgis/openstreetmap.de#40]
The website in the shop window for Yapis gets redirected from http://yapis.geoclub.de to https://www.geoclub.de/forum/

https://github.com/fossgis/openstreetmap.de/blob/e71b858018e8f1319983a6dead2f4552f6050180/layouts/shortcodes/shop-window.html#L203=

Does Yapis not exist anymore? Is there a successor project available?

**Comment by TheFireCircle** [comment]
Sorry, but I don't know any successor project.
I'll remove this entry. Maybe someone else knows something about this project.
