### ISSUE TITLE
Link 'About Style' funktioniert nicht

### ISSUE THREAD

**Issue by lonvia** [fossgis/openstreetmap.de#44]
Auf https://openstreetmap.de/karte/ gibt es unten rechts in der Ecke einen Link 'About style', der nach https://openstreetmap.de/karte/germanstyle.html führt. Da bekomme ich einen 404.

Ausserdem wäre es natürlich gut, wenn der Linktext in Deutsch ist.

**Comment by giggls** [comment]
Die Karte bräuchte halt auch einen Redesign. Stammt glaube ich unverändert aus dem alten Design. Jedenfalls gab es die Datei da mal.

**Comment by pka** [comment]
Habe die Seite https://openstreetmap.de/germanstyle.html in cbcbbd6 wiederhergestellt. Sie wird auch von den FOSSGIS-Förderprojekten her referenziert. Damit der Link in der Karte stimmt, braucht es einen "Shift-Reload", damit map.js aktualisiert wird.
