### ISSUE TITLE
Automatische Aktualisierung der usergroups (kml Datei)

### ISSUE THREAD

**Issue by gislars** [fossgis/openstreetmap.de#6]
Es wird eine KML-Datei für die Usergroups als Overlay eingebunden. Diese Datei wird nicht automatisch aktualisiert. Auf usergroups.openstreetmap.de wird auf Basis des OSM-Wiki Group Template automatisiert das KML generiert. 

Eine Lösung wäre ein Cronjob auf osm.de

(Hier aufgeschrieben damit es nicht untergeht. )

**Comment by gmbo** [comment]
Da könne ein Einzeiler reichen.
`wget -o melde.txt -O a.kml 'usergroups.openstreetmap.de/osm_user_groups.kml';echo '<?xml version="1.0" encoding="utf-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>OSM usergroups worldwide</name><description>Generated list of OpenStreetMap local user groups by UserGroupsBot</description><Style id="usergroup"><IconStyle><Icon><href>localgroup.png</href><scale>0.5</scale></Icon></IconStyle></Style>' >de.kml;sed  "s/<\/Placemark>/<\/Placemark>\n/g" a.kml |sed "s/<Placemark/\n<Placemark/"|grep "<country>DE</country>" >>de.kml;echo '</Document></kml>' >>osm_user_groups_dach.kml`

**Comment by it4workflow** [comment]
Nachdem es ja eher in talk-de diskutiert wurde, auch hier noch meine Anmerkung:
Das Pythonskript auf usersgroups.openstreetmap.de erzeugt neben dem worldwide KML auch bereits eine DACH KML, die man in der Tat entweder nur an die richtige Stelle kopieren müsste, oder wenn es nun so vorgesehen ist, nach jeder Änderung einen git pull request erstellt, oder was auch immer sich die Admins so vorgestellt haben

**Comment by it4workflow** [comment]
Alternativ wie in der talk-de Diskussion angesprochen, könnte man den "Lokale Gruppen" Layer aus der Karte entfernen und unter "Community">"Lokale Gruppen" einen deutlicheren Hinweis und Link auf das existierende usergroups.openstreetmap.de hinterlegen

**Comment by Nakaner** [comment]
it4workflow schrieb:
> Alternativ wie in der talk-de Diskussion angesprochen, könnte man den "Lokale Gruppen" Layer aus der Karte entfernen und unter "Community">"Lokale Gruppen" einen deutlicheren Hinweis und Link auf das existierende usergroups.openstreetmap.de hinterlegen

Dann kann man das auch gleich bleiben lassen. Glaubst du, dem Link folgt jemand? Durch die prominente Platzierung der Marker in der jetzigen Form erwecken wir einen aktiven, persönlichen Eindruck.

**Comment by gmbo** [comment]
Ich würde das auch drin lassen.
usergroups.openstreetmap.de  hat zur Zeit noch den Fehler der fehlenden Cowboys?

> Error in loading GML file cowboys.kml
Verstehe nur waage was das auf .de macht.

Wenn doch das Python Script schon die richtige Datei erzeugt, dann sollte der Pullreqest in der /js/markers.js gemacht werden auf das richtige Ziel und eventuell ein Fallback auf die veraltete statische Liste.

**Comment by Nakaner** [comment]
Die cowboys.kml war die Liste der Orte, an der im Rahmen der [Operation Cowboy ](https://wiki.openstreetmap.org/wiki/DE:Operation_Cowboy) Mapathons stattfanden.

**Comment by gmbo** [comment]
Das ist schon klar, aber warum ist die kml-Datei dann nicht mehr da wo sie war oder warum hat man es dort nicht komplett entfernt.

**Comment by it4workflow** [comment]
Habe die cowboys.kml und auch die Einbindung in der Layerübersicht nun entfernt.

**Comment by Nakaner** [comment]
Quasi-Follow-Up von https://github.com/fossgis/openstreetmap.de/pull/15

Wir haben auf der FOSSGIS-Vorstandssitzung (Mumble) heute Abend kurz darüber diskutiert. Der Usergroups-Bot läuft auf Gauss, einem der drei Strato-Servern, welcher im Laufe diesen Jahres abgeschaltet werden wird. Da der Bot selbst wenig Last erzeugt, wird man ihn einfach irgendwohin umziehen.

Unabhängig davon, wann und wohin man ihn umzieht, möchte ich den FOSSGIS-Vorstand darum bitten, Max Techter damit zu beauftragen würde, per Cronjob zweimal täglich, http://usergroups.openstreetmap.de/osm_user_groups_DACH.kml und http://usergroups.openstreetmap.de/osm_user_groups_DACH.json auf den www-Server in den DocumentRoot kopieren. Im Gegenzu löschen wir dann die KML-Datei mit `git rm` in diesem Repository.

@giggls @woodpeck

**Comment by Nakaner** [comment]
@woodpeck Gibt es da Neuigkeiten oder soll ich selber ein Skript schreiben, das bloß noch deployt werden muss?

**Comment by osmtools** [comment]
zur Info: https://github.com/fossgis/usergroups-bot/pull/1 ist abgeschlossen

**Comment by Nakaner** [comment]
Die feste Datei hier habe ich gelöscht. Es wird jetzt eine verwendet, die täglich von usergroups.openstreetmap.de per Cronjob kopiert wird.
