### ISSUE TITLE
MTB "Single-Trails" erscheinen als Radwege

### ISSUE THREAD

**Issue by hungerburg** [fossgis/openstreetmap.de#61]
In meiner Nähe gibt es einige reine Mountainbike Abfahrtsstrecken. Die rendern sehr prominent als Radwege. ZB https://www.openstreetmap.org/way/441558821 (Ich merk gerade, ich kann von der DE Karte keinen Direktlink auf einen Ausschnitt erstellen).

Am tagging seh ich dort alles Bestens. In naher Zukunft wird GraphHopper dort niemanden entlangschicken, der einfach nur mit dem Rad von A nach B will. Man ist dort fast von selbst drauf gekommen. Ich würde es gut finden, wenn die auf der DE Karte nicht wie Radwege aussehen. Vielleicht lässt sich da ja etwas machen?

**Comment by giggls** [comment]
Das gehört hier nicht her. Issues zum deutschen Kartenstil wären prinzipiell hier richtig:
https://github.com/giggls/openstreetmap-carto-de

Da ich aber zufällig der Maintainer des deutschen forks des OSM Carto Stiels bin schreibe ich hier einfach mal warum das so ist. Der Weg wurde mit bicycle = designated getaggt stellt also einen Radweg dar und wird deshalb auch so gerendert.

Kein Fehler im Kartenstil aus meiner Sicht, denn nach meiner Interpretation des taggings ist highway=path+bicycle=designated+foot=no äquivalent zu highway=cycleway.

Gruss

Sven
